library(hexbin)
qqplot_hex <- function(nl_oP,nl_dP1,title,alpha=FALSE,beta=" by coverage"){	
	s_nl_oP <- sort(nl_oP,decreasing=F)
	s_nl_dP <- sort(nl_dP1,decreasing=F)
	q_nl_oP <- quantile(s_nl_oP,probs=seq(0,1,length.out=length(s_nl_oP)))
	q_nl_dP <- quantile(s_nl_dP,probs=seq(0,1,length.out=length(s_nl_oP)))
	bin <- hexbin(q_nl_dP,q_nl_oP,xbins=400,xlab=expression(paste("-log(P",scriptstyle(null),")")),ylab=expression(paste("-log(P",scriptstyle(obs),")")))
	if (alpha != FALSE){
		main_tit=bquote(paste(.(title), alpha,"=",.(alpha)," ", beta,.(beta)))
		}
	else{
		main_tit=bquote(.(title))
	}
	pp<-plot(bin,legend=FALSE,style="constant.col",main=main_tit)
	
	hvp=hexViewport(bin)
	hexVP.abline(hvp,0,1,col="red",lty=2)
}

source("/Volumes/Temp/Lukas/Tools/Scripts/R/manhattan_plot_all_chromosomes_function_qqplot.R")
colnames(data)
setwd("/Volumes/Temp/Lukas/Data/Vienna_2011/Polymorphisms_Filtered/CMH")
data <- read.table("fem_vie2011_pI25_pII25_pIII25_pIp_pIIp_pIIIp_filtered_q20_masked_mc8_only_chroms_mct15_mcv25_nlpl1.gwas", header=TRUE)
data$ID <- paste(data$CHR,data$BP,sep="_")
quartz(height=6,width=12)
par(bg="white")
chroms=c("X","2L","2R","3L","3R","4")#,"XHet","2LHet","2RHet","3LHet","3RHet")
manhattan(data,colors=c("black","slategrey"),limitchromosomes=chroms,main="Vienna 2011")
dev.print(png,width=800,file="vie2011_filtered_manhattan.png")

setwd("/Volumes/Temp/Lukas/Data/Vienna_2010/Polymorphisms_Filtered/CMH")
data<- read.table("females_pI25_pII25_pIII25_pIel_pIIel_pIIIel_q20_filtered_masked_mc7_only_chroms_noAceto_mct15_mcv25_nlpl1.gwas",header=T)
data$ID <- paste(data$CHR,data$BP,sep="_")
quartz(height=6,width=12)
par(bg="white")
chroms=c("X","2L","2R","3L","3R","4")#,"XHet","2LHet","2RHet","3LHet","3RHet")
manhattan(data,colors=c("black","slategrey"),limitchromosomes=chroms,main="females, Vienna 2010")
dev.print(png,width=800,file="vie2010_filtered_manhattan.png")

setwd("/Volumes/Temp/Lukas/Data/Vienna_2010/Realigned/Real_poly/CMH")
data<- read.table("females_pI18_pII18_pIel_pIIel_realigned_q20_filt_mc4_chroms_only_mct4_mcv25.gwas",header=T)
data$ID <- paste(data$CHR,data$BP,sep="_")
quartz(height=6,width=12)
par(bg="white")
chroms=c("X","2L","2R","3L","3R","4")#,"XHet","2LHet","2RHet","3LHet","3RHet")
manhattan(data,colors=c("black","slategrey"),limitchromosomes=chroms,main="females, Vienna 2010, CS 18C",suggestiveline=c(-log10(2.022e-08)))
dev.print(png,width=800,file="vie2010_cs18_filtered_manhattan.png")
quartz()
nl_oP = -1 * log10(data$P)
nl_unif = -1 *log10(runif(length(nl_oP)))
qqplot_hex(nl_oP,nl_unif,title="Vienna 2010 females CS18 against uniform")
pdf(file="qq_unif_vie2010_CS18.pdf")


setwd("/Volumes/Temp/Lukas/Data/Vienna_2010_male/Polymorphisms/CMH")
data<- read.table("male_2010_pICS25_pIICS25_pIIICS25_pIE_pIL_pIIIE_q20_masked_mc1.5_mct10_mcv20_nlpl0.75.gwas",header=T)
data$ID <- paste(data$CHR,data$BP,sep="_")
quartz(height=6,width=12)
par(bg="white")
chroms=c("X","2L","2R","3L","3R","4")#,"XHet","2LHet","2RHet","3LHet","3RHet")
manhattan(data,colors=c("black","slategrey"),limitchromosomes=chroms,main="males, Vienna 2010")
dev.print(png,width=800,file="vie2010_males_manhattan.png")

setwd("/Volumes/Temp/Lukas/Data/Vienna_2010/BaseComparison/Polymorphisms/CMH")
data<- read.table("fem_bases_2010_pIe_pIIe_pIIIe_pIl_pIIl_pIIIl_q20_masked_mc8_repeats_mct12_mcv25_nlpl0.8.gwas",header=T)
data$ID <- paste(data$CHR,data$BP,sep="_")
quartz(height=6,width=12)
par(bg="white")
chroms=c("X","2L","2R","3L","3R","4")#,"XHet","2LHet","2RHet","3LHet","3RHet")
manhattan(data,colors=c("black","slategrey"),limitchromosomes=chroms,main="comparison of early and late eclosion, females Vienna 2010")
dev.print(png,width=800,file="vie2010_bases_manhattan.png")

setwd("/Volumes/Temp/Lukas/Data/Vienna_2011/Realigned/Poly_Real/CMH")
data <- read.table("females11_pI25_pII25_pIII25_pIhl_pIIhl_pIIIhl_realigned_q20_filt_mc8_chroms_only_mct8_mcv25_nlpl1.gwas",header=TRUE)
data <- read.table()"females11_pI25_pII25_pIII25_pIhl_pIIhl_pIIIhl_realigned_q20_filt_mc8_chroms_only_mct8_mcv25.gwas", header=TRUE)
data$ID <- paste(data$CHR,data$BP,sep="_")
quartz(height=6,width=12)
par(bg="white")
chroms=c("X","2L","2R","3L","3R","4")#,"XHet","2LHet","2RHet","3LHet","3RHet")
manhattan(data,colors=c("black","slategrey"),limitchromosomes=chroms,main="Bolzano (2011)", suggestiveline=c(-log(2.203e-08)))
dev.print(png,width=800,file="vie2011_filtered_manhattan.png")

setwd("/Volumes/Temp/Lukas/Data/Vienna_2010_male/Polymorphisms/CMH/")
data <- read.table("male_2010_pI_IICS25_pIIICS25_pIEL_pIIIE_q20_masked_mc1.5_mct8_mcv25.gwas",header=TRUE)
data$ID <- paste(data$CHR,data$BP,sep="_")
quartz(height=6,width=12)
par(bg="white")
chroms=c("X","2L","2R","3L","3R","4")#,"XHet","2LHet","2RHet","3LHet","3RHet")
manhattan(data,colors=c("black","slategrey"),limitchromosomes=chroms,main="Vienna males CS (2010)", suggestiveline=c(-log10(3.25385e-08)))
dev.print(png,width=800,file="vie2010_males_manhattan.png")
quartz()
nl_oP = -1 * log10(data$P)
nl_unif = -1 *log10(runif(length(nl_oP)))
qqplot_hex(nl_oP,nl_unif,title="Vienna 2010 males CS against uniform")
dev.copy2pdf(file="qq_unif_vie2010_males.pdf")


nullP=scan("/Volumes/Temp/Lukas/Data/Vienna_2011/Realigned/Poly_Real/CMH/FDR/females11_pI25_pII25_pIII25_pIhl_pIIhl_pIIIhl_realigned_q20_filt_mc8_chroms_only_mct8_mcv25.cmhout_a_22.0_beta_r1_43.56_r2_87.04_r3_167.30_nullP.out")
quartz()
hist(nullP,bins=500)
nullP=scan("/Volumes/Temp/Lukas/Data/Vienna_2011//Polymorphisms_Filtered/CMH/FDR/fem_vie2011_pI25_pII25_pIII25_pIp_pIIp_pIIIp_filtered_q20_masked_mc8_only_chroms_mct15_mcv25.cmhout_a_21.5_beta_r1_42.57_r2_84.75_r3_163.00_nullP.out")
quartz()
hist(nullP,bins=500)

setwd("/Volumes/Temp/Lukas/Data/Vienna_2010/Realigned/Real_poly/CMH")
obsP<- scan("FDR/females_pI25_pII25_pIII25_pIel_pIIel_pIIIel_realigned_q20_filt_mc8_chroms_only_mct8_mcv25.cmhout.pVals")
nullP <- scan("FDR/females_pI25_pII25_pIII25_pIel_pIIel_pIIIel_realigned_q20_filt_mc8_chroms_only_mct8_mcv25.cmhout_a_27.0_beta_r1_38.70_r2_61.96_r3_104.14_nullP.out")
quartz()
nl_oP = -1 * log10(obsP)
nl_null = -1 *log10(nullP)
qqplot_hex(nl_oP,nl_null,title="Vienna 2010 females CS25", alpha=27.0)
dev.copy2pdf(file="qq_a27_b_cov_vie2010_CS25.pdf")
nullP <- scan("FDR/females_pI25_pII25_pIII25_pIel_pIIel_pIIIel_realigned_q20_filt_mc8_chroms_only_mct8_mcv25.cmhout_a_26.0_beta_r1_37.27_r2_59.67_r3_100.29_nullP.out")
quartz()
nl_oP = -1 * log10(obsP)
nl_null = -1 *log10(nullP)
qqplot_hex(nl_oP,nl_null,title="Vienna 2010 females CS25", alpha=26.0)
dev.copy2pdf(file="qq_a26_b_cov_vie2010_CS25.pdf")
nullP <- scan("FDR/females_pI25_pII25_pIII25_pIel_pIIel_pIIIel_realigned_q20_filt_mc8_chroms_only_mct8_mcv25.cmhout_a_36.0_beta_r1_51.60_r2_82.62_r3_138.86_nullP.out10x")
quartz()
nl_oP = -1 * log10(obsP)
nl_null = -1 *log10(nullP)
qqplot_hex(nl_oP,nl_null,title="Vienna 2010 females CS25, null 10x ", alpha=36.0)
dev.copy2pdf(file="qq_a36_b_cov_vie2010_CS25_10x.pdf")
nullP <- scan("FDR/females_pI25_pII25_pIII25_pIel_pIIel_pIIIel_realigned_q20_filt_mc8_chroms_only_mct8_mcv25.cmhout_a_35.0_beta_r1_50.17_r2_80.32_r3_135.00_nullP.out10x")
quartz()
nl_oP = -1 * log10(obsP)
nl_null = -1 *log10(nullP)
qqplot_hex(nl_oP,nl_null,title="Vienna 2010 females CS25, null 10x ", alpha=35.0)
dev.copy2pdf(file="qq_a35_b_cov_vie2010_CS25_10x.pdf")



# shuffled bases
nullP <- scan("Shuffle/females_pI25_pII25_pIII25_pIel_pIIel_pIIIel_realigned_q20_filt_mc8_chroms_only_mct8_mcv25.cmhout1_3_4_5_4_6_nullP.out")
nullP <- scan("Shuffle/all_bases_shuff.out")

nl_null = -1 *log10(nullP)
quartz()
qqplot_hex(nl_oP,nl_null,title="Vienna 2010 females CS25, shuffled 1_3_4_5_4_6 ")
dev.copy2pdf(file="qq_shuffled_vie2010_CS25.pdf")
quartz()

