setwd("/Volumes/Temp/Lukas/Data/Coverage_Comp/")
sa_a7=read.table("/Volumes/Temp/Lukas/Data/SA_A7/Polymorphisms/sa_a7_VL1_VL4_VL5_L1_L4_L5_DVD1_DVD4_DVD5_VVD1_VVD4_VVD5_q20_filt_mc2_2L_5MB.win100.cov",header=F)
field_sa=unlist(strsplit("VL1_VL4_VL5_L1_L4_L5_DVD1_DVD4_DVD5_VVD1_VVD4_VVD5","_"))
colnames(sa_a7)=c("CHR","BPS",field_sa)
gc_cont=read.table("gc_content_ws_100_from5000.tab",header=F,skip=1)
colnames(gc_cont)=c("CHR","BPS","GC")
gc_cont = subset(gc_cont, CHR == "2L")
chill_coma10=read.table("/Volumes/Temp/Lukas/Data/Vienna_2010/Realigned/Real_poly/females_pI25_pII25_pIII25_pIel_pIIel_pIIIel_realigned_q20_filt_mc8_2L_5MB.win_100.cov",header=F)
field_cc10=unlist(strsplit("pI25_pII25_pIII25_pIel_pIIel_pIIIel","_"))
colnames(chill_coma10)=c("CHR","BPS",field_cc10)


chill_coma11=read.table("/Volumes/Temp/Lukas/Data/Vienna_2011/Realigned/Poly_Real/females11_pI25_pII25_pIII25_pIhl_pIIhl_pIIIhl_realigned_q20_filt_mc8_2L.win_100.cov",header=F)
field_cc11=unlist(strsplit("pI25_pII25_pIII25_pIhl_pIIhl_pIIIhl","_"))
colnames(chill_coma11)=c("CHR","BPS",field_cc11)

trid_ita11=read.table("/Volumes/Temp/Lukas/Data/Trident/Italy/Polymorphisms/males_ita11_pTL1_pTL2_pTL3_pTD1_pTD2_pTD3_q20_filt_mc2_2L_5MB.win_100.cov",header=F)
field_trid11=unlist(strsplit("pTL1_pTL2_pTL3_pTD1_pTD2_pTD3","_"))
colnames(trid_ita11)=c("CHR","BPS",field_trid11)


quartz(height=6,width=12)
plot(sa_a7$BPS,sa_a7$VL1,xlim=c(2.5e6,2.55e6),type="l",col="red",ylim=c(0,250),ylab="coverage",xlab="Chrom 2L",main="Coverage 100 bp windows")
lines(sa_a7$BPS,sa_a7$VVD4,type="l",col="green")
lines(trid_ita11$BPS,trid_ita11$pTL1,type="l",col="blue")
legend("topright",c("BGI65:ATCACGAT","BGI66:ACTTGAAT","BGI62:CGATGTAT"),lty=c(1,1,1),col=c("red","green","blue"))
dev.copy2pdf(file="coverage_window100_BGI62_65_66.pdf")
plot(sa_a7$BPS,sa_a7$VL1,xlim=c(2.5e6,2.55e6),type="l",col="red",ylim=c(0,200),ylab="coverage",xlab="Chrom 2L",main="Coverage 100 bp windows")
lines(chill_coma10$BPS,chill_coma10$pIel,type="l",col="green")
lines(chill_coma11$BPS,chill_coma11$pIhl,type="l",col="blue")
legend("topright",c("BGI65:ATCACGAT","Run15&Run19","BGI2"),lty=c(1,1,1),col=c("red","green","blue"))
dev.copy2pdf(file="coverage_window100_BGI65_Run15_19_BGI12.pdf")

lines(sa_a7$BPS,sa_a7$VVD1,type="l",col="blue")
lines(chill_coma10$BPS,chill_coma10$pI25,type="l",col="pink")
lines(chill_coma11$BPS,chill_coma11$pI25,type="l",col="red")
lines(trid_ita11$BPS,trid_ita11$pTL1,type="l",col="black")
plot(chill_coma11$BPS,chill_coma11$pIhl,xlim=c(2.5e6,2.55e6),type="l",col="red",ylim=c(0,300))

quartz(height=6,width=12)
par(mar = c(5, 4, 4, 4) + 0.3)  # Leave space for z axis
plot(sa_a7$BPS,sa_a7$VL1,xlim=c(2.5e6,2.55e6),type="l",col="red",ylim=c(0,250),ylab="coverage",xlab="Chrom 2L",main="Coverage 100 bp windows") # first plot
par(new = TRUE)
plot(gc_cont$BPS, gc_cont$GC, type = "l",xlim=c(2.5e6,2.55e6), ylim=c(0.2,0.8),axes = FALSE, bty = "n", xlab = "", ylab = "", col = "blue")
axis(side=4, at = pretty(range(0,1)))
mtext("GC content", side=4, line=3)
legend("topright",c("BGI65:ATCACGAT","GC content"),lty=c(1,1,1),col=c("red","blue"))
dev.copy2pdf(file="coverage_window100_BGI65_GC.pdf")

joined_gc=merge(gc_cont,subset(sa_a7,select = c(BPS,VL1)),by="BPS")
joined_gc=merge(joined_gc,subset(trid_ita11,select = c(BPS,pTL1)),by="BPS")
joined_gc=merge(joined_gc,subset(chill_coma11,select = c(BPS,pI25,pIhl)),by="BPS")
joined_gc=merge(joined_gc,subset(chill_coma10,select = c(BPS,pIel,pIIel)),by="BPS")
cor(joined_gc$GC,joined_gc$VL1)
cor(joined_gc$GC,joined_gc$pTL1)
cor(joined_gc$GC,joined_gc$pI25)
cor(joined_gc$GC,joined_gc$pIhl)
cor(joined_gc$GC,joined_gc$pIel)
cor(joined_gc$GC,joined_gc$pIIel)
cov(joined_gc$GC,joined_gc$VL1)
cov(joined_gc$GC,joined_gc$pTL1)
cov(joined_gc$GC,joined_gc$pI25)
cov(joined_gc$GC,joined_gc$pIhl)
cov(joined_gc$GC,joined_gc$pIel)
cov(joined_gc$GC,joined_gc$pIIel)
quartz(height=6,width=12)
par(mar = c(5, 4, 4, 4) + 0.3)  # Leave space for z axis
plot(chill_coma10$BPS,chill_coma10$pIel,xlim=c(2.5e6,2.55e6),type="l",col="red",ylim=c(0,250),ylab="coverage",xlab="Chrom 2L",main="Coverage 100 bp windows") # first plot
lines(chill_coma10$BPS,chill_coma10$pIIel,type="l",col="green")
par(new = TRUE)
plot(gc_cont$BPS, gc_cont$GC, type = "l",xlim=c(2.5e6,2.55e6), ylim=c(0.2,0.8),axes = FALSE, bty = "n", xlab = "", ylab = "", col = "blue")
axis(side=4, at = pretty(range(0,1)))
mtext("GC content", side=4, line=3)
legend("topright",c("chill coma 10 (Iel)","chill coma 10 (IIel)","GC content"),lty=c(1,1,1),col=c("red","green","blue"))
dev.copy2pdf(file="coverage_window100_ChillComa10_GC.pdf")
